46 investor notification system development optional
Project-Stage-Academy/UA_1155_alpha pull request #95
Opened 2024-05-04 13:23 UTC by AlexanderSychev2005

1) Added notification system (model for notifications, celery task for creating notifications objects in mongodb and email an investor about project updating).
2) Implemented and configured Celery and Redis.
![image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/49594203/f1003996-a2a6-41cd-b506-f51e82a0a16d)
![image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/49594203/e417ef77-df2e-486f-aa89-14d221873757)
![image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/49594203/c02a8f67-bc9f-4af4-8cbb-2a81553a3b1f)
![image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/49594203/a29db88f-dca0-4592-85ec-02a7dbdd23f4)

2024-05-07 12:06 UTC, NovitskaMariia reviewed
Everything works fine. Just a little proposition for improvement:
 - I think, it`ll be better to change endpoint for notifications like this: "api/notifications/new". Because we can see here only new notifs.
 - After that we can add endpoint for all notifs. Like that:  "api/notifications/all". I'm not sure if our project's logic require this endpoint, because investor can see old notifications in his email. We can discuss it with team.
 - Please, add instructions from your PR to the .env.example for our team, and change REDIS_URL=redis://127.0.0.1:6379/0.

2024-05-07 12:07 UTC, NovitskaMariia approved these changes

2024-05-07 19:52 UTC, VovaD199 approved these changes

2024-05-08 17:22 UTC, NovitskaMariia requested changes
on the endpoint api/notifications/new/ I can`t see any notifs :(

![image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/133953467/24b796fb-92ee-4d48-9d7d-3a86c91330bb)

If I send Get method again, I'll see another message
![image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/133953467/cef7c554-96fd-4b36-89c7-9442449ac377)
 
And in Mongo is_read become true:
![image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/133953467/79269d6f-5f47-45d2-a9b8-80c47e0e7227)

The api/notifications/all/ endpoint works perfect ;)
![image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/133953467/c88441e1-5eb9-422d-9d07-5d9bcef940ad)

2024-05-08 18:11 UTC, NovitskaMariia approved these changes

2024-05-09 15:23 UTC, Thoughtseize1 approved these changes
Add some information and commands to Wiki, please if you didn't.

2024-05-09 15:31 UTC, merged